# Generated by Django 5.1.6 on 2025-03-19 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0002_rename_phone_accountinfo_phonenumber_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('streetName', models.CharField(max_length=200)),
                ('addressLine1', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=50)),
                ('accountInfo_userid', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'address',
            },
        ),
    ]
