# Generated by Django 5.1.6 on 2025-04-18 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0003_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountinfo',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='accountinfo',
            name='profileImage',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
