# Generated by Django 5.1.6 on 2025-05-07 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0004_alter_accountinfo_phonenumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountinfo',
            name='email',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='accountinfo',
            name='userName',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
